sudo: false
language: ruby
rvm:
  - 2.4.0
before_install:
  - gem install bundler -v 1.13.7
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token:
      secure: po7qSwRDd1arNn5QPIwhq4M6GsjQx5jN35Cqjgfvf9YSYRdoTJBi7pfhC/OK6i7K6tFoDKQl9HkRvwfjLF9qrP1HSdGCewkuqnlstCGAtR1B5fLP08WVhBP/UlCq2A9Ai/jU+owU/aq7hMsYUU9xikUblL3kdu3M5/AOMKh3fjWOYqK5NOO+FTUrCCBFNnOVEVYv4S9BiXopczQlGEgF2YLXgoHH4+8tvbf/kWsmRk74/1BigltvbTmRMQHiu6rROFfZIE4Krt6no/a0CP09EjCyCSNWzrqPrOhhbT1SNrKDMiQqoW3OEBHEyvTiufzKMOEJJqVOQUjO34I5aZI3QzKEup0PkvWSXsb2/FOkYsSNOXgv4822mzgktdgJYxft58jAx1ogzWq+P15vBspMWtpMDcEoUFHUShGzoiCbKrIF/59BVy0eKHMIwlXSqmOYuSOr2i/nmfI0nJbfoQM3t4+Haxr45rijUuyPTVVL0O+2CdTBoDNGbpdjasm7h2iPE137sEXGTe3pWrBipkmf8VEeST/vpln+HLwpXQzPBepR9etC+AURHW1xQvufd1yZV0lONY97xmsCm+JOTRRz5+c/Tp3SzYvciUzon/56ogjT1Lg3P6FGpQo/UXaCiM9//aBeCR0cpgMpBeoMPaItNlfwsCSB9qbD9HTSKVD3FRI=
